classrooms/urls.py
from django.urls import path
from .views import ClassroomListView,ClassroomDetailView

app_name='classrooms'

urlpatterns = [
    path("", ClassroomListView.as_view(), name="list"),
    path("<int:pk>/", ClassroomDetailView.as_view(), name="detail")
]

exams/urls.py
from django.urls import path
from . import views

app_name='exams'

urlpatterns = [
    #path("", views.HomeView.as_view(), name="home"),
    path("", views.ExamListView.as_view(), name="list"),
    path("<int:pk>/", views.ExamDetailView.as_view(), name="detail"),
    path("create/", views.ExamCreateView.as_view(), name="create"),
    path("solutions", views.ExamSolutionListView.as_view(), name="solutions_list"),
    path("<int:pk>/solutions", views.ExamSolutionDetailView.as_view(), name="solutions_detail")
]

sis/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.BaseView.as_view(),name='base'),
    path('home/',views.HomeView.as_view(),name='home'),
    path("exams/", include('exams.urls')),
    path("classrooms/", include('classrooms.urls')),
    path("users/", include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("students/", views.StudentListView.as_view(), name="student_list"),
    path("students/<int:pk>/", views.StudentDetailView.as_view(), name="student_detail"),
    path("teachers/", views.TeacherListView.as_view(), name="teacher_list"),
    path("teachers/<int:pk>/", views.TeacherDetailView.as_view(), name="teacher_detail"),
    path("students/<int:pk>/exam/<int:pk2>/<int:pk3>", views.QTemplateView.as_view(),name="q_solution")
]

templates/base/footer.html
<footer class="footer">
    <div class="container">
      <span class="text-muted">footer.</span>
    </div>
  </footer>

templates/base/navbar.html
<nav class="navbar navbar-expand-md navbar-light bg-nav fixed-top">
    <div class="container-fluid">
        <div class="row w-100">
            <div class="col-2">
                <a href="/" class="navbar-brand bg-mix mr-5"><i class="fas fa-school"></i> School</a>
            </div>
            <div class="col-10">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar5">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse justify-content-stretch" id="navbar5">
                    <ul class="navbar-nav ml-0"> <!-- ml-5 -->
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Link <span class="sr-only">Home</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="">Link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav mx-auto">
                        <div class="row w-100">
                            <div class="col">
                                <li class="nav-item d-inline w-100">
                                    <form class="input-group">
                                        <div class="input-group" style="width: 500px;">
                                            <input type="text" class="form-control border-right-0"
                                                placeholder="Search for students, teachers, exams and more">
                                            <div class="input-group-append">
                                                <button class="btn btn-warning border-left-0" type="button">Search</button>
                                            </div>
                                        </div>
                                    </form>
                                </li>
                            </div>
                        </div>
                        
                        <!-- <form class="d-block w-100">
                        <div class="input-group">
                            <input type="text" class="form-control border-right-0" placeholder="...">
                            <div class="input-group-append">
                                <button class="btn btn-outline-primary border-left-0" type="button">GO</button>
                            </div>
                        </div>
                    </form> -->
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">{{ request.user.username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">logout</a>
                        </li>
                        {% else %}
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</nav>

templates/base/sidebar.html
{% url 'exams:list' as examlist %}
{% url 'home' as home %}
{% url 'classrooms:list' as classroomlist %}
{% url 'users:student_list' as studentlist %}
{% url 'users:teacher_list' as teacherlist %}
<nav class="navbar navbar-light bg-sidebar ssidebar">
    <div class="container pt-0 mt-0">
        <ul class="navbar-nav pt-0">
            <li class="nav-item dropdown py-2">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Dashboard
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item active" href="#">Admin</a>
                    <a class="dropdown-item" href="#">Teacher</a>
                    <a class="dropdown-item" href="#">Student</a>
            </li>
            <li class="nav-item {% if request.path == home %}active mx-auto{%endif%} py-2">
                <a class="nav-link" href="{{ home }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.path == examlist %}active mx-auto{%endif%} py-2">
                <a class="nav-link" href="{% url 'exams:list' %}">Exams</a>
            </li>
            <li class="nav-item {% if request.path == classroomlist %}active mx-auto{%endif%} py-2">
                <a class="nav-link" href="{{ classroomlist }}">Classrooms</a>
            </li>
            <li class="nav-item {% if request.path == studentlist %}active mx-auto{%endif%} py-2">
                <a class="nav-link" href="{{ studentlist }}">Students</a>
            </li>
            <li class="nav-item {% if request.path == teacherlist %}active mx-auto{%endif%} py-2">
                <a class="nav-link" href="{{ teacherlist }}">Teachers</a>
            </li>
            <li class="nav-item py-2">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item py-2">
                <a class="nav-link" href="#">Link</a>
            </li>
        </ul>
    </div>
   
    <nav>