classrooms/urls.py
from django.urls import path
from .views import ClassroomListView,ClassroomDetailView

app_name='classrooms'

urlpatterns = [
    path("", ClassroomListView.as_view(), name="list"),
    path("<int:pk>/", ClassroomDetailView.as_view(), name="detail")
]

sis/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.BaseView.as_view(),name='base'),
    path('home/',views.HomeView.as_view(),name='home'),
    path("exams/", include('exams.urls')),
    path("classrooms/", include('classrooms.urls')),
    path("users/", include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("students/", views.StudentListView.as_view(), name="student_list"),
    path("students/<int:pk>/", views.StudentDetailView.as_view(), name="student_detail"),
    path("teachers/", views.TeacherListView.as_view(), name="teacher_list"),
    path("teachers/<int:pk>/", views.TeacherDetailView.as_view(), name="teacher_detail"),
    path("students/<int:pk>/exam/<int:pk2>/<int:pk3>", views.QTemplateView.as_view(),name="q_solution")
]

classrooms/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from users.models import Teacher

# Create your models here.

class Classroom(models.Model):
    grade = models.IntegerField(validators=[MaxValueValidator(9)])
    section = models.CharField(max_length=1)
    advisor = models.OneToOneField(Teacher,on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.grade}-{self.section}'
    

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


# Create your models here.

class Teacher(models.Model):

    class Subject(models.TextChoices):
        TURKCE = 'T', _('Turkce')
        SOSYAL = 'S', _('Sosyal')
        MATEMATIK = 'M', _('Matematik')
        FEN = 'F', _('Fen')
        DEFAULT = 'Q', _('Default')

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    subject = models.CharField(max_length=1, choices=Subject.choices, default=Subject.DEFAULT)#max_length=1,
    joined_date = models.DateTimeField() # timestamp
    phone = models.CharField(max_length=11)

    def __str__(self):
        return self.user.username
    

class Student(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    stud_id = models.PositiveSmallIntegerField()
    joined_date = models.DateTimeField() # timestamp
    classroom = models.ForeignKey('classrooms.Classroom', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

classrooms/views.py
from django.shortcuts import render
from django.views import generic
from .models import Classroom


class ClassroomListView(generic.ListView):
    model = Classroom


class ClassroomDetailView(generic.DetailView):
    model = Classroom

classrooms/templates/classrooms/classroom_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">

    <div class="jumbotron">
        <h1>{{ object }}</h1>
    </div>
    <div class="row">
        <div class="col-8 mx-auto">
            <ul>
            {% for student in classroom.student_set.all %}
              <li><a href="{% url 'classrooms:detail' pk=object.pk %}"><a href="{% url 'users:student_detail' pk=student.pk %}"> {{ student.user.username }}</a></a></li>
            {% empty %}
              <p>There are no students in this class atm</p>
            {% endfor %}
            </ul>
        </div>
    </div>
            
</div>
{% endblock content %}

classrooms/templates/classrooms/classroom_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">

    <div class="jumbotron">
        <h1>Classrooms</h1>
    </div>
    <div class="row">
        <div class="col-8 mx-auto">
            <ul>
            {% for object in object_list %}
              <li><a href="{% url 'classrooms:detail' pk=object.pk %}">{{ object }}</a></li>
            {% empty %}
              <p>There are no classrooms atm</p>
            {% endfor %}
            </ul>
        </div>
    </div>
            
</div>
{% endblock content %}