classrooms/urls.py
from django.urls import path
from .views import ClassroomListView,ClassroomDetailView

app_name='classrooms'

urlpatterns = [
    path("", ClassroomListView.as_view(), name="list"),
    path("<int:pk>/", ClassroomDetailView.as_view(), name="detail")
]

exams/urls.py
from django.urls import path
from . import views

app_name='exams'

urlpatterns = [
    #path("", views.HomeView.as_view(), name="home"),
    path("", views.ExamListView.as_view(), name="list"),
    path("<int:pk>/", views.ExamDetailView.as_view(), name="detail"),
    path("create/", views.ExamCreateView.as_view(), name="create"),
    path("solutions", views.ExamSolutionListView.as_view(), name="solutions_list"),
    path("<int:pk>/solutions", views.ExamSolutionDetailView.as_view(), name="solutions_detail")
]

sis/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.BaseView.as_view(),name='base'),
    path('home/',views.HomeView.as_view(),name='home'),
    path("exams/", include('exams.urls')),
    path("classrooms/", include('classrooms.urls')),
    path("users/", include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("students/", views.StudentListView.as_view(), name="student_list"),
    path("students/<int:pk>/", views.StudentDetailView.as_view(), name="student_detail"),
    path("teachers/", views.TeacherListView.as_view(), name="teacher_list"),
    path("teachers/<int:pk>/", views.TeacherDetailView.as_view(), name="teacher_detail"),
    path("students/<int:pk>/exam/<int:pk2>/<int:pk3>", views.QTemplateView.as_view(),name="q_solution")
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


# Create your models here.

class Teacher(models.Model):

    class Subject(models.TextChoices):
        TURKCE = 'T', _('Turkce')
        SOSYAL = 'S', _('Sosyal')
        MATEMATIK = 'M', _('Matematik')
        FEN = 'F', _('Fen')
        DEFAULT = 'Q', _('Default')

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    subject = models.CharField(max_length=1, choices=Subject.choices, default=Subject.DEFAULT)#max_length=1,
    joined_date = models.DateTimeField() # timestamp
    phone = models.CharField(max_length=11)

    def __str__(self):
        return self.user.username
    

class Student(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    stud_id = models.PositiveSmallIntegerField()
    joined_date = models.DateTimeField() # timestamp
    classroom = models.ForeignKey('classrooms.Classroom', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

users/views.py
from django.shortcuts import render
from django.views import generic
from .models import Student, Teacher
from exams.models import Exam, ExamResult, ExamSolution, QSolution
import json
# Create your views here.


class StudentListView(generic.ListView):
    model = Student

# class ModalTemplateView(generic.TemplateView):
#     template_name="users/snippets/student/modal.html"

#     def get_context_data(self,*args, **kwargs):
#         context = super().get_context_data(*args,**kwargs)
#         context["a"] = 'adgadgad'
#         return context
        

class StudentDetailView(generic.DetailView):
    model = Student

    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        student = context.get('object')
        context['last_exams_results'] = student.exam_results.all().reverse()[:5]
        if student.user.first_name and student.user.last_name is not None:
            context['fullname'] = f'{student.user.first_name} {student.user.last_name}'
        context['exams_all'] = student.exam_results.all()
        # mat_list = []
        # for result in student.exam_results.all():
        #     mat_list.append(20-len(result.result['Yanlislar']['M']))
        # context['mat_yanlislar'] = mat_list
        context['mat_yanlislar'] = get_yanlis_count(student,"M")
        context['fen_yanlislar'] = get_yanlis_count(student,'F')
        context['sosyal_yanlislar'] = get_yanlis_count(student,'S')
        context['turkce_yanlislar'] = get_yanlis_count(student,'T')
        context['success_status'] = success_status(student)
        context['image'] = student.exam_results.filter(exam__title='LGS HAZIRLIK - 5').first().exam.solutions.first().solutions.solution.url
        #student.exam_results.first().exam.solutions.first().solutions.solution.url

        # item_dict = json.loads(json.dumps(context['exams_all'].first().result))
        # print (len(item_dict['Yanlislar']['M']))
        #context['exams_all_results'] = Exam.objects.filter(result__student=student)
        return context


class TeacherListView(generic.ListView):
    model = Teacher


class TeacherDetailView(generic.DetailView):
    model = Teacher


class QTemplateView(generic.TemplateView):
    template_name="users/snippets/student/modals/q_modal.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["q"] = 'Q_Q'
        return context
    


def get_net_count(student,ders,*args, **kwargs):
    net=0
    for result in student.exam_results.all():
        yanlis_list.append(20-len(result.result["Yanlislar"][ders]))
    return yanlis_list

def get_yanlis_count(student,ders,*args, **kwargs):
    yanlis_list = []
    for result in student.exam_results.all():
        Exam.objects.filter(id=result.exam_id).evaluate(student.pk,Exam.objects.filter(id=result.exam_id).first().pk)
        yanlis_list.append(20-len(result.result["Yanlislar"][ders]))
    return yanlis_list

def success_status(student):
    success=""
    last=""
    between=""
    mean=0
    last2_mean=0
    for index,exam in enumerate(ExamResult.objects.filter(student=student)):
        if index >= ExamResult.objects.filter(student=student).count() - 2:
            last2_mean += int(exam.result['Net'])  
        mean+=int(exam.result['Net'])
    mean = mean / (ExamResult.objects.filter(student=student).count())
    last2_mean /= 2 
    if 70 < mean < 80:
        success="basarili"
        if last2_mean < mean:
            between="fakat"
        else:
            between="ve"
    elif 60 < mean < 70:
        success="vasat"
        if last2_mean < mean:
            between="ve"
        else:
            between="fakat"
    else:
        success="basarisiz"
        if last2_mean < mean:
            between="ve"
        else:
            between="fakat"
    if last2_mean < mean:
        last="dususte"
    else:
        last="yukseliste"
    #between = "ve" if 70 < mean < 80 and last2_mean > mean else "fakat" || "fakat" if mean < 70 and last2_mean > mean else "ve" ! Check nested ternary operator
    print(f' sounc -> {success} {between} {last}')
    return f'{success} {between} {last}'
    

users/templates/users/student_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="row">

    <!-- CHART -->
    <div class="col-5">
        <div class="row">
            <div class="col-8 mx-auto">
                <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
                    <label class="btn btn-secondary active">
                        <input type="radio" name="options" id="option1" checked> son 5
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option2"> this month(ders bazli)
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option3"> Tum Denemeler
                    </label>
                </div>
            </div>
        </div>
        <div class="row pt-3">
            <div class="col">
                <canvas id="myChart2" width="450" height="275"></canvas> <!-- width="450" -->
                <canvas id="myChart3" style="display:none;" width="450" height="275"></canvas> <!-- width="450" -->
                <!-- modal -->
            </div>
        </div>
    </div>

    <!-- INFO -->
    <div class="col-3">
        <div class="alert alert-warning" role="alert">
            <h2>Info </h2>
            <hr>
            {% if object.user.first_name %}
            <p>Name : {{ object.user.first_name }}</p>
            <p>Surname : {{ object.user.last_name }}</p>
            {% else %}
            <p>Name : {{ object.user.username }}</p>
            {% endif %}
            <p>Sinif : {{ object.classroom }}</p>
            <!-- Basari durumu(basarili,vasat,basarisiz) : Custom managermodel and queryset and define success_rate() filter based on exams etc -->
            <p>Basari durumu : {{ success_status }}</p>
            <p>Advisor : <a href=""> {{ object.classroom.advisor }}</a></p>
        </div>
        <!-- <div class="row">
            <div class="col">
                <div class="alert alert-primary" role="alert">
                    <h2>Contact Info </h2>
                    <hr>
                    <p>Advisor Name: <a href=""> {{ object.classroom.advisor.user.username }}</a></p>
                    <p>Advisor email: <a href=""> {{ object.classroom.advisor.user.email }}</a></p>
                    <p>Advisor Phone: <a href=""> {{ object.classroom.advisor.phone }}</a></p>
                </div>
            </div>
        </div> -->
    </div>

    <!-- EXAM RESULST TABLE -->
    <div class="col-4">
        <h1>last 5 exam results</h1>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Net</th>
                    <th scope="col">Puan</th>
                    <th scope="col">Sinif</th>
                    <th scope="col">Tarih</th>
                </tr>
            </thead>
            <tbody>
                {% if last_exams_results %}
                {% for exam_result in last_exams_results  %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>
                        {% comment %} data-target=".bd-example-modal-lg" {% endcomment %}
                        <a href="{% url 'exams:solutions_detail' pk=exam_result.pk %}" data-toggle="modal"
                            data-target="#myModal{{ exam_result.exam.id }}">{{ exam_result.exam }}</a>
                    </td>
                    <td>{{ exam_result.result.Net|floatformat }}</td>
                    <td>450</td>
                    <td><a href="">{{ exam_result.student.classroom }}</a></td>
                    <td>{{ exam_result.exam.timestamp|date:"d M, Y" }}</td>
                </tr>
                {% include 'users/snippets/student/modal.html' with student=object result=exam_result exam=exam_result.exam img=image %}
                {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>

</div>

<div class="row pt-3">

    <!-- CALENDAR -->
    <div class="col-8">
        <h3>Ders Programi </h3>
        {% include 'base/snippets/calendar.html' %}
    </div>

    <!-- INFO -->
    <div class="col-4">
        <div class="row">
            <div class="col-8 mx-auto">
                <div class="alert alert-warning" role="alert">
                    <h2>Info </h2>
                    <hr>
                    <p>Name : {{ object.user.username }}</p>
                    <p>Surname : {{ object.user.lastname }}</p>
                    <p>Sinif : {{ object.classroom }}</p>
                    <p>Basari durumu(basarili,vasat,basarisiz) : Custom managermodel and queryset and define
                        success_rate() filter based on exams etc</p>
                    <p>Advisor : <a href=""> {{ object.classroom.advisor }}</a></p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-8 mx-auto">
                <div class="alert alert-primary" role="alert">
                    <h2>Contact Info </h2>
                    <hr>
                    <p>Advisor Name: <a href=""> {{ object.classroom.advisor.user.username }}</a></p>
                    <p>Advisor email: <a href=""> {{ object.classroom.advisor.user.email }}</a></p>
                    <p>Advisor Phone: <a href=""> {{ object.classroom.advisor.phone }}</a></p>
                </div>
            </div>
        </div>
    </div>

</div>

<script src="{% static 'js/main.js' %}"></script>
<!-- <script>new Chart(document.getElementById("myChart2"),{"type":"line","data":{"labels":[{% for exam_result in exams_all  %}'{{exam_result.exam.title}},{{exam_result.exam.timestamp|date:"d M Y"}}',{% endfor %}],"datasets":[{"label":"Net Sayisi","data":[{% for y in mat_yanlislar %}'{{ y }}',{% endfor %}],"fill":false,"borderColor":"rgb(75, 192, 192)","lineTension":0.1}]},"options":{responsive:true,scales: {yAxes: [{ticks: {min: 0,max:20}}]}}});</script> -->
<script>
    var chart = new Chart(document.getElementById("myChart2"), {
        "type": "line",
        "data": {
            "labels": [{% for exam_result in exams_all %}'{{exam_result.exam.title}},{{exam_result.exam.id}}',{% endfor %}],// |cut:" HAZIRLIK" ,{{exam_result.exam.timestamp|date:"d M Y"}}
    "datasets": [
        {
            "label": "Net Sayisi",
            "data": [{% for exam_result in exams_all %}'{{ exam_result.result.Net|floatformat }}', {% endfor %}],
        "fill": false,
            "borderColor": "rgb(75, 192, 192)",
                "lineTension": 0.1
                    }
                ]
            },
    "options": {
        responsive: true,
            scales: {
            xAxes: [{
                ticks: {
                    callback: function (value) {
                        //value.indexOf(',')
                        return value.substr(0, 4) + value.substr(value.length - 4, value.length);//truncate
                    },
                    fontSize: 10
                }
            }],
                yAxes: [{
                    ticks: {
                        min: 50, max: 80
                    }
                }]
        },
        legend: {
            labels: {
                fontColor: 'red',
                fontSize: 5
            }
        },
        // This chart will not respond to mousemove, etc
        //events: ['click']
    }});

    var myChart3 = new Chart(document.getElementById("myChart3"), {
        "type": "bar",
        "data": {
            "labels": [{% for exam_result in exams_all %}'{{exam_result.exam.title}}',{% endfor %}],// |cut:" HAZIRLIK" ,{{exam_result.exam.timestamp|date:"d M Y"}}
    "datasets": [
        {
            "label": "Matematik Net",
            "data": [{% for y in mat_yanlislar %}'{{ y }}', {% endfor %}],
        "fill": false,
            "backgroundColor": "rgba(255, 99, 132, 0.2)",
                "borderColor": "rgb(175, 255, 192)",
                    "lineTension": 0.1
                    },
    {
        "label": "Fen Net",
            "data": [{% for y in fen_yanlislar %} '{{ y }}', {% endfor %}],
    "fill": false,
        "backgroundColor": "rgba(255, 150, 132, 0.2)",
            "borderColor": "rgb(68, 225, 192)",
                "lineTension": 0.1
                    },
    {
        "label": "Sosyal Net",
            "data": [{% for y in sosyal_yanlislar %} '{{ y }}', {% endfor %}],
    "fill": false,
        "backgroundColor": "rgba(255, 99, 50, 0.2)",
            "borderColor": "rgb(175, 155, 192)",
                "lineTension": 0.1
                    },
    {
        "label": "Turkce Net",
            "data": [{% for y in turkce_yanlislar %} '{{ y }}', {% endfor %}],
    "fill": false,
        "backgroundColor": "rgba(0, 99, 132, 0.2)",
            "borderColor": "rgb(175, 0, 255)",
                "lineTension": 0.1
                    },
                ]
            },
    "options": { responsive: true, scales: { yAxes: [{ ticks: { min: 0, max: 20 } }], xAxes:[{ticks:{fontSize:10}}] } }});

    document.getElementById("myChart2").onclick = function (evt) {
        var activePoints = chart.getElementsAtEvent(evt);
        console.log('activePoints', activePoints)
        console.log(activePoints)
        if (activePoints.length > 0) {
            //get the internal index of slice in pie chart
            var clickedElementindex = activePoints[0]["_index"];

            //get specific label by index 
            var label = chart.data.labels[clickedElementindex];

            //get value by index      
            var value = chart.data.datasets[0].data[clickedElementindex];

            console.log(label)
            var examId = label.substr(label.indexOf(',')+1,label.length)
            console.log(examId)
            /* other stuff that requires slice's label and value */
            $('#myModal'+examId).modal('show');
  
        }
    }

    document.getElementById("myChart3").onclick = function (evt) {
        var activePoints = chart.getElementsAtEvent(evt);
        console.log(activePoints)
        if (activePoints.length > 0) {
            //get the internal index of slice in pie chart
            var clickedElementindex = activePoints[0]["_index"];

            //get specific label by index 
            var label = chart.data.labels[clickedElementindex];

            //get value by index      
            var value = chart.data.datasets[0].data[clickedElementindex];

            console.log(label)
            /* other stuff that requires slice's label and value */
        }
    }

    // function random_rgba() {
    // var o = Math.round, r = Math.random, s = 255;
    // return 'rgba(' + o(r()*s) + ',' + o(r()*s) + ',' + o(r()*s) + ',' + r().toFixed(1) + ')';
    // }
    // console.log(random_rgba())
    // var ctx = document.getElementById('myChart2');
    // var ctx = 'myChart2'
    // var myChart = new Chart(ctx, {
    //     type: 'bar',
    //     data: {
    //         labels: [{% for exam_result in exams_all  %}'{{exam_result.exam.title}},{{exam_result.exam.timestamp|date:"d M Y"}}',{% endfor %}],//{% for obj in exam_results.reverse  %}'{{obj.title}}',{% endfor %}
    //         datasets: [{
    //             label: 'Net', // katilimedge0fs
    //             data: [{% for exam_result in exams_all %}'{{ exam_result.result.Net }}',{% endfor %}], //{% for result in exam_results_results %}'{{result}}',{% endfor %}  {% for result in exam_results.reverse.result.all  %}'{{ result.result }}',{% endfor %}
    //             backgroundColor: [{% for result in exams_all_results  %}random_rgba(),{% endfor %}
    //                 //'rgba(255, 99, 132, 0.2)',
    //                 //'rgba(54, 162, 235, 0.2)',
    //                 //'rgba(255, 206, 86, 0.2)',
    //             ],
    //             borderColor: [{% for result in exam_results_results %}random_rgba(),{% endfor %}
    //                 //'rgba(255, 99, 132, 1)',
    //                 //'rgba(54, 162, 235, 1)',
    //                 //'rgba(255, 206, 86, 1)',
    //             ],
    //             borderWidth: 1
    //         }]
    //     },
    //     options: {
    //         scales: {
    //             yAxes: [{
    //                 ticks: {
    //                     beginAtZero: true,
    //                     max: 80
    //                 }

    //             }]
    //         }
    //     }
    // });</script>
{% endblock content %}

users/templates/users/student_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    {% for student in object_list  %}
    <div class="col">
        <a href="{% url 'users:student_detail' pk=student.pk %}">{{ student.user.first_name|title }} {{ student.user.last_name|upper }}</a>
    </div>
    {% empty %}
    <p>there are no students atm</p>
    {% endfor %}
</div>
{% endblock content %}

users/templates/users/teacher_detail.html
{% extends 'base.html' %}
{% block content %}
{% load teacher_extras %}
<div class="row">
    <div class="col-2">
        <div class="alert alert-warning" role="alert">
            <h2>Info </h2>
            <hr>
            <p>Name : {{ object.user.first_name }}</p>
            <p>Surname : {{ object.user.last_name }}</p>
            <p>Subject : {{ object.subject|label }}</p>
            <p>Sorumlu Sinif : <a href="{% url 'classrooms:detail' pk=object.classroom.pk %}">{{ object.classroom }}</a></p>
        </div>
    </div>
    <div class="col-3">
        <div class="alert alert-primary" role="alert">
            <h2>Contact Info </h2>
            <hr>
            <p>Email: <a href=""> {{ object.user.email }}</a></p>
            <p>Phone: <a href=""> {{ object.phone }}</a></p>
        </div>
    </div>
    <div class="col-3">
        <h2>Contributed Exams</h2>
        <hr>
        <p>Total contributions: {{ object.contributed_solutions.all.count }}</p>
        
        <p>Contributed exams: {% for exam_solution in object.contributed_solutions.all %} {% ifchanged %} {{ exam_solution.exam }} {% endifchanged %} {% empty %} None {% endfor %}</p> <!-- {{ object.contributed_solutions.exam.all.distinct }} -->
        <hr>
        <a href="" class="btn btn-secondary btn-sm">Add Solution</a>
    </div>
    <div class="col-4 ml-auto">
        <h2>last 3 exam results (sorumlu oldugu sinifa gore sirala ?)</h2>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Net</th>
                    <th scope="col">Puan</th>
                    <th scope="col">Sinif</th>
                    <th scope="col">Tarih</th>
                </tr>
            </thead>
            <tbody>
                {% if last_exams_results %}
                {% for exam in last_exams_results  %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href="">{{ exam.exam }}</a></td>
                    <td>{{ exam.result }}</td>
                    <td>450</td>
                    <td><a href="">{{ exam.student.classroom }}</a></td>
                    <td>{{ exam.exam.timestamp|date:"d M, Y" }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <th scope="row">1</th>
                    <td>Mark Otto</td>
                    <td>30</td>
                    <td>450</td>
                    <td>A</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>Jacob Thornton lenghtehend btch</td>
                    <td>40</td>
                    <td>430</td>
                    <td>B</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>Larry the bird</td>
                    <td>50</td>
                    <td>410</td>
                    <td>C</td>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-8">
        <h3>Event Calendar </h3>
        {% include 'base/snippets/calendar.html' %}
    </div>
</div>
{% endblock content %}

users/templates/users/teacher_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    {% for teacher in object_list  %}
    <div class="col">
        <a href="{% url 'users:teacher_detail' pk=teacher.pk %}">{{ teacher.user.username }}</a>
    </div>
    {% empty %}
    <p>there are no teachers atm</p>
    {% endfor %}
</div>
{% endblock content %}