classrooms/urls.py
from django.urls import path
from .views import ClassroomListView,ClassroomDetailView

app_name='classrooms'

urlpatterns = [
    path("", ClassroomListView.as_view(), name="list"),
    path("<int:pk>/", ClassroomDetailView.as_view(), name="detail")
]

exams/urls.py
from django.urls import path
from . import views

app_name='exams'

urlpatterns = [
    #path("", views.HomeView.as_view(), name="home"),
    path("", views.ExamListView.as_view(), name="list"),
    path("<int:pk>/", views.ExamDetailView.as_view(), name="detail"),
    path("create/", views.ExamCreateView.as_view(), name="create"),
    path("solutions", views.ExamSolutionListView.as_view(), name="solutions_list"),
    path("<int:pk>/solutions", views.ExamSolutionDetailView.as_view(), name="solutions_detail")
]

sis/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.BaseView.as_view(),name='base'),
    path('home/',views.HomeView.as_view(),name='home'),
    path("exams/", include('exams.urls')),
    path("classrooms/", include('classrooms.urls')),
    path("users/", include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("students/", views.StudentListView.as_view(), name="student_list"),
    path("students/<int:pk>/", views.StudentDetailView.as_view(), name="student_detail"),
    path("teachers/", views.TeacherListView.as_view(), name="teacher_list"),
    path("teachers/<int:pk>/", views.TeacherDetailView.as_view(), name="teacher_detail"),
    path("students/<int:pk>/exam/<int:pk2>/<int:pk3>", views.QTemplateView.as_view(),name="q_solution")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>sis</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/calendar.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'js/main.js' %}"> -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.js"></script>

    <!-- <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"> -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
    <!-- {% include 'base/snippets/test.html' %} -->
</head>

<body>
    {% include 'base/navbar.html' %}
    <!-- style="min-height: 1200px;"> -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-4 col-md-3 col-lg-2 px-0 pt-0 mt-0 sidebar"> <!-- style="background-image: url({% static 'css/forest.jpg' %});" -->
                {% include 'base/sidebar.html' %}
            </div>
            <div class="col-8 col-md-9 col-lg-10 pt-5 pl-0 content">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>

    <div class="fixed-bottom bg-light">
        {% include 'base/footer.html' %}
    </div>
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col">
        <div class="jumbotron-fluid">
            <div class="alert alert-warning" role="alert">
               <a href="{% url 'users:student_list' %}"> <i class="fas fa-user-graduate"></i>  Students  </a> | {{ student_count }}
            </div>
        </div>
    </div>
    <div class="col">
        <div class="jumbotron-fluid">
            <div class="alert alert-primary" role="alert">
               <a href="{% url 'users:teacher_list' %}"> <i class="fas fa-chalkboard-teacher"></i>  Teachers </a> | {{ teacher_count }}
            </div>
        </div>
    </div>
    <div class="col">
        <div class="jumbotron-fluid">
            <div class="alert alert-info" role="alert">
               <a href=""><i class="fas fa-users-cog "></i>  Principals </a>  | {{ principal_count }} 
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-7">
        <h3>Event Calendar</h3>
        {% include 'base/snippets/calendar.html' %}
    </div>
    <div class="col-5">
        {% if last_exam %}
            <h3><a href="{% url 'exams:detail' pk=last_exam.pk %}">last exam results</a></h3>
            <table class="table table-striped table-hover dash-table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Net</th>
                    <th scope="col">Puan</th>
                    <th scope="col">Sinif</th>
                    <th scope="col">Sube</th>
                </tr>
                </thead>
                <tbody>
                    {% for result in last_exam.result.all|slice:":10" %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td><a href="{% url 'users:student_detail' pk=result.student.pk %}">{{ result.student.user.first_name }} {{ result.student.user.last_name }}</a></td>
                            <td>{{ result.result.Net|floatformat }}</td>
                            <td>450</td>
                            <td><a href="{% url 'classrooms:detail' pk=result.student.classroom.pk %}">{{ result.student.classroom }}</a></td>
                            <td>{{ result.student.classroom.section }}</td>
                        </tr>
                    {% endfor %}
                        <tr>
                            <td colspan="6" style="text-align: center;"> <a href="{% url 'exams:detail' pk=last_exam.pk %}"><p>see the full results</p></a></td>
                        </tr>
                {% else %}
                    <p>no exams took place yet</p>
                {% endif %}
            </tbody>
          </table>
          <h3><a href="">student overall progress</a></h3>
          <canvas id="myChart" style="font-size : 10px;" width="400" height="275"></canvas>
    </div>
</div>
<div class="row">
    <div class="col">
        {% for result in exam_results_results %}<p>{{result}}</p>{% endfor %}
        {% for obj in exam_results  %}
            <p>{{ obj.title }}</p>
            {% comment %} <p>{{ exam_results_results }}</p> {% endcomment %}
            {% for result in obj.result.all %}
                <p>{{ result.result }}</p>
            {% endfor %}
        {% endfor %}
        <h2><a href="">{{ exam_results }}</a></h2>
    </div>
</div>
<script>
    function random_rgba() {
    var o = Math.round, r = Math.random, s = 255;
    return 'rgba(' + o(r()*s) + ',' + o(r()*s) + ',' + o(r()*s) + ',' + r().toFixed(1) + ')';
    }
    console.log(random_rgba())
    var ctx = document.getElementById('myChart');
    var ctx = 'myChart'
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: [{% for exam in exams_all  %}'{{exam.title}},{{exam.timestamp|date:"d M Y"}}',{% endfor %}],//{% for obj in exam_results.reverse  %}'{{obj.title}}',{% endfor %}
            datasets: [{
                label: 'Net Ortalamalari', // katilimedge0fs
                data: [{% for result in exams_all_results  %}'{{ result }}',{% endfor %}], //{% for result in exam_results_results %}'{{result}}',{% endfor %}  {% for result in exam_results.reverse.result.all  %}'{{ result.result }}',{% endfor %}
                backgroundColor: [{% for result in exams_all_results  %}random_rgba(),{% endfor %}
                    //'rgba(255, 99, 132, 0.2)',
                    //'rgba(54, 162, 235, 0.2)',
                    //'rgba(255, 206, 86, 0.2)',
                ],
                borderColor: [{% for result in exam_results_results %}random_rgba(),{% endfor %}
                    //'rgba(255, 99, 132, 1)',
                    //'rgba(54, 162, 235, 1)',
                    //'rgba(255, 206, 86, 1)',
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            },
            // layout: {
            //     padding: {
            //         left: 50,
            //         right: 50,
            //         top: 50,
            //         bottom: 50
            //     }
            // }
        }
    });</script>
{% endblock content %}

templates/vue_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>sis</title>
</head>
<body>
     <div id="app">
        <h1>{{ product }}</h1>
    </div>
    
    <script src="https://unpkg.com/vue"></script>
    <script>
        var app = new Vue({
            el:'#app',
            data:{
                product:'bla'
            }
        })
    </script>
</body>
</html>